#!/usr/bin/env python

import sys
from functools import reduce

text = reduce(lambda acc, line: acc + "\n" + line, sys.stdin, "")

tokens = text.split()

for t in tokens:
    print(f"\"{t}\", ", end="")

